import numpy as np
from sklearn.preprocessing import normalize
        
def txt_to_dict(filename):
    header = ''
#     Get the names of the features we will be extracting
    with open(filename) as f:
        header = next(f).split('\t')[1:]
#     Load the .txt file generated by matlab into python, omitting the header
    textfile_as_array = np.loadtxt(filename, skiprows=1, converters={0:lambda x: x[:-4]})
    song_ids = textfile_as_array[:,0].astype(int)
#     Normalize
    not_normalized = np.array([row for row in textfile_as_array.T if not np.isnan(row[0])])
    features = normalize(not_normalized, norm='l1', axis=1).T
#     Return the song ids and the features as a dictionary
    return(header, dict(zip(song_ids, features)))